THISDIR=py/getexch
TOPDIR=../..
DIST=${TOPDIR}/dist/plato

edb:
	shellcheck edb.sh

clean:
	echo "Done in ${THISDIR}"

test:
	echo "Done in ${THISDIR}"

package:
	mkdir -p ${DIST}
	cp *.sh *.py ${DIST}/
